# Generated by Django 4.1.4 on 2022-12-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя Факультета')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='TypeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип обучения')),
            ],
            options={
                'verbose_name': 'Тип обучения',
                'verbose_name_plural': 'Типы обучения',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='id telegram')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('department', models.IntegerField(default=99)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя направления')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(verbose_name='Описание образования')),
                ('faculties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='CampAdmin.faculties', verbose_name='факультеты')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='CampAdmin.profile', verbose_name='профили')),
                ('type_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='CampAdmin.typeeducation', verbose_name='типы образования')),
            ],
            options={
                'verbose_name': 'Описание профиля',
                'verbose_name_plural': 'Описание профилей',
                'unique_together': {('type_education', 'faculties', 'profile')},
            },
        ),
    ]
